"""Siemens EEPROM identities, storage formats, and diffs."""

from .battery import (
    BATTERY_CALIBRATION_BLOCK,
    BATTERY_CALIBRATION_LENGTH,
    CEMU_DEFAULT_BATTERY_CALIBRATION,
    AffineCorrection,
    BatteryCalibration,
    decode_battery_calibration,
    encode_battery_calibration,
    load_battery_calibration,
    synthesize_battery_calibration,
)
from .corpus import (
    CORPUS_SCHEMA,
    CORPUS_SCHEMA_VERSION,
    analyze_corpus,
    discover_sources,
    render_corpus,
)
from .diff import BlockDiff, DiffResult, diff_sources, render_block_bytediff
from .identity import (
    bcd_imei_to_normal,
    create_imei_records,
    create_unlocked_plaintexts,
    crc_check_bytes,
    generate_identity_bundle,
    generate_overlay_bundle,
    imei_check_digit,
    recreate_imei,
    recreate_imei_companion,
    verify_checks,
)
from .profiles import (
    A52_EMULATOR_MINIMAL_PROFILE,
    A52_EMULATOR_MINIMAL_V1,
    A55_EMULATOR_MINIMAL_PROFILE,
    A55_EMULATOR_MINIMAL_V1,
    A60_EMULATOR_MINIMAL_PROFILE,
    A60_EMULATOR_MINIMAL_V1,
    A62_EMULATOR_MINIMAL_PROFILE,
    A62_EMULATOR_MINIMAL_V1,
    A65_EMULATOR_MINIMAL_PROFILE,
    A65_EMULATOR_MINIMAL_V1,
    C55_EMULATOR_MINIMAL_PROFILE,
    C55_EMULATOR_MINIMAL_V1,
    C60_EMULATOR_MINIMAL_PROFILE,
    C60_EMULATOR_MINIMAL_V1,
    CF62_EMULATOR_MINIMAL_PROFILE,
    CF62_EMULATOR_MINIMAL_V1,
    EEPROM_PROFILES,
    EepromProfile,
    M55_EMULATOR_MINIMAL_PROFILE,
    M55_EMULATOR_MINIMAL_V1,
    MC60_EMULATOR_MINIMAL_PROFILE,
    MC60_EMULATOR_MINIMAL_V1,
    SL55_EMULATOR_MINIMAL_PROFILE,
    SL55_EMULATOR_MINIMAL_V1,
    S55_EMULATOR_MINIMAL_PROFILE,
    S55_EMULATOR_MINIMAL_V1,
    ProfileRecord,
    get_eeprom_profile,
)
from .security import (
    B5008_LEN,
    B5009_LEN,
    B5077_LEN,
    BUNDLE_PROFILE,
    BUNDLE_SCHEMA,
    MODEL_ID7_KEY1_ALIASES,
    MODEL_KEY1,
    UNKNOWN_KEY1_C55,
    convert_to_bcd,
    decrypt_5008,
    decrypt_5077,
    encrypt_5008,
    encrypt_5077,
    parse_fsn,
)
from .storage import (
    BLOCKHEADER_LEN,
    DEFAULT_REGION_LINEAR_BASE,
    EEPROM_BANK_STRIDES,
    Block,
    BlockEntry,
    EepromRegion,
    block_class,
    extract_block,
    find_eeprom_region,
    load_dump_blocks,
    load_eeprom_source,
    looks_like_map,
    parse_directory,
    parse_directory_records,
    parse_map_file,
    serialize_block,
)

__all__ = [name for name in globals() if not name.startswith("_")]
